# Generated by Django 3.1.3 on 2023-05-18 00:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='friendship',
            index_together={('to_user_id', 'created_at'), ('from_user_id', 'created_at')},
        ),
    ]
